using Arcen.AIW2.Core;
using Arcen.Universal;
using System;

using System.Text;
using UnityEngine;

namespace Arcen.AIW2.External
{/// <summary>
 /// Normal chat messages, generated by a player or the game itself.
 /// </summary>
    public class GameCommand_Chat : BaseGameCommand
    {
        public override void Execute( GameCommand command, ArcenClientOrHostSimContextCore context )
        {
            if ( command.RelatedString.Length > 0 )
            {
                if (command.RelatedFInts.Count > 0)
                    Engine_Universal.WriteToLocalMomentaryDisplayLog( command.RelatedString, command.ClickHandlerOrNull, command.RelatedFInts.First.ToFloatNonSim() );
                else
                    Engine_Universal.WriteToLocalMomentaryDisplayLog( command.RelatedString, command.ClickHandlerOrNull );

                World_AIW2.Instance.WriteToLongTermChatLog( command.RelatedString, command.ClickHandlerOrNull );
            }

            if ( command.RelatedString2 != null && command.RelatedString2.Length > 0 )
            {
                //                ArcenDebugging.ArcenDebugLogSingleLine("Trying to play line " + command.RelatedString2, Verbosity.DoNotShow );
                SFXItem sfxItem = SFXItemTable.Instance.GetRowByNameOrNullIfNotFound( command.RelatedString2 );
                if ( sfxItem != null )
                {
                    Engine_AIW2.Instance.PresentationLayer.PlayVoiceAtCamera( SoundPropagation.PlayLocallyOnly, sfxItem );
                }
                // else
                //{
                //     //Note: this needs to be the name of the XML entry in CMP_SFXItems
                //     ArcenDebugging.ArcenDebugLogSingleLine("could not find line", Verbosity.DoNotShow );
                //}
            }
        }
    }
    /// <summary>
    /// Execute a command, or cheat code!
    /// </summary>
    public class GameCommand_ChatCommand : BaseGameCommand
    {
        public override void Execute( GameCommand command, ArcenClientOrHostSimContextCore context )
        {
            if ( command.RelatedString.Length > 0 )
            {
                int debugStage = 0;
                try
                {
                    debugStage = 100;
                    Int16 planetIndex = (Int16)command.RelatedIntegers2.First;
                    debugStage = 200;
                    Planet planet = World_AIW2.Instance.GetPlanetByIndex( planetIndex );
                    debugStage = 300;
                    Int16 factionIndex = 0;
                    byte playerAccountID = 0;
                    int _ri3_i = 0;
                    foreach ( var _ri3_v in command.RelatedIntegers3 )
                    {
                        if ( _ri3_i == 0 ) factionIndex = (Int16)_ri3_v;
                        else if ( _ri3_i == 1 ) { playerAccountID = (byte)_ri3_v; break; }
                        _ri3_i++;
                    }
                    debugStage = 400;
                    Faction faction = World_AIW2.Instance.Factions[factionIndex];
                    debugStage = 500;
                    debugStage = 600;
                    PlayerAccount pAccount = World.Instance.GetPlayerAccountByPrimaryID( playerAccountID );

                    debugStage = 33300;
                    CheatsAndCommands.ProcessCheatOrCommandText( command.RelatedString2, command.RelatedString, planet, faction, pAccount, context );
                }
                catch ( Exception e )
                {
                    ArcenDebugging.ArcenDebugLogSingleLine( "Hit exception in GameCommand ChatCommand. debugStage " + debugStage + " " + e.ToString(), Verbosity.ShowAsError );
                }
            }
        }
    }

    /// <summary>
    /// Log a journal entry!
    /// </summary>
    public class GameCommand_JournalEntry : BaseGameCommand
    {
        public override void Execute( GameCommand command, ArcenClientOrHostSimContextCore context )
        {
            string uniqueNameToUseIfGroupNotPresent = command.RelatedString;
            string optionalGroupID = command.RelatedString2;
            string relatedUnitTypeOrNull = command.RelatedString3;
            Int16 relatedFactionIndexOrNull = (Int16)command.RelatedIntegers.First;
            Int16 relatedPlanetOrNull = (Int16)command.RelatedIntegers2.First;

            JournalEntry entryToUse = null;
            bool isOkayIfNoDirectNameSpecified = false;

            #region First Look By The Group If We Can
            if ( optionalGroupID != null && optionalGroupID.Length > 0 )
            {
                isOkayIfNoDirectNameSpecified = true;
                if ( !JournalEntryTable.Instance.GroupedEntries.CheckIfAlreadyHasKey( optionalGroupID ) )
                    ArcenDebugging.ArcenDebugLogSingleLine( "Journal oops!  Could not find any entries with OptionalGroupID of '" + optionalGroupID + "'", Verbosity.ShowAsError );
                else
                {
                    List<JournalEntry> entries = JournalEntryTable.Instance.GroupedEntries[optionalGroupID];
                    if ( entries.Count == 0 )
                        ArcenDebugging.ArcenDebugLogSingleLine( "Journal oops!  Empty list of entries with OptionalGroupID of '" + optionalGroupID + "'", Verbosity.ShowAsError );
                    else if ( entries.Count == 1 )
                    {
                        entryToUse = entries[0];
                        entryToUse = entryToUse.GetEntryToUseInCurrentCampaign(); //if we can't use it, null ourselves out... OR find an alt internally based on its logic
                    }
                    else
                    {
                        int randomIndex = context.RandomToUse.Next( 0, entries.Count );

                        for ( int i = randomIndex; i < entries.Count; i++ )
                        {
                            if ( entryToUse != null )
                                break; //if we found a good match, then stop!
                            entryToUse = entries[i];
                            entryToUse = entryToUse.GetEntryToUseInCurrentCampaign(); //if we can't use it, null ourselves out... OR find an alt internally based on its logic
                        }
                        if ( entryToUse == null )
                        {
                            for ( int i = 0; i < randomIndex; i++ )
                            {
                                if ( entryToUse != null )
                                    break; //if we found a good match, then stop!
                                entryToUse = entries[i];
                                entryToUse = entryToUse.GetEntryToUseInCurrentCampaign(); //if we can't use it, null ourselves out... OR find an alt internally based on its logic
                            }
                        }
                    }
                }
            }
            #endregion

            //if we didn't already get one from the group, try by the direct name / unique ID
            if ( entryToUse == null )
            {
                if ( uniqueNameToUseIfGroupNotPresent != null && uniqueNameToUseIfGroupNotPresent.Length > 0 )
                {
                    if ( !JournalEntryTable.Instance.EntriesByUniqueName.ContainsKey( uniqueNameToUseIfGroupNotPresent ) )
                        ArcenDebugging.ArcenDebugLogSingleLine( "Journal oops!  Could not find any entries with name / uniqueID of '" + uniqueNameToUseIfGroupNotPresent + "'", Verbosity.ShowAsError );
                    else
                    {
                        entryToUse = JournalEntryTable.Instance.EntriesByUniqueName[uniqueNameToUseIfGroupNotPresent];
                        entryToUse = entryToUse.GetEntryToUseInCurrentCampaign(); //if we can't use it, null ourselves out... OR find an alt internally based on its logic
                    }
                }
                else
                {
                    if ( !isOkayIfNoDirectNameSpecified )
                        ArcenDebugging.ArcenDebugLogSingleLine( "Journal oops!  Looks like no name or group was specified to log to the journal? (Name: '" + uniqueNameToUseIfGroupNotPresent + "', optionalGroupID: '" + optionalGroupID + "')", Verbosity.ShowAsError );
                }
            }

            //this can validly be null if all the versions have been logged and there was no alt.  In which case journal nothing, that's just fine.
            if ( entryToUse != null )
            {
                //first up, log this thing centrally for everyone
                JournalEntryInCampaign entryWithData = JournalEntryInCampaign.GetFromPoolOrCreate();
                entryWithData.UniqueID = entryToUse.InternalName;
                entryWithData.GameSecondLogged = World_AIW2.Instance.GameSecond;
                entryWithData.RelatedEntityType = relatedUnitTypeOrNull;
                entryWithData.RelatedFactionIndex = relatedFactionIndexOrNull;
                entryWithData.RelatedPlanetID = relatedPlanetOrNull;
                entryWithData.IsTipRatherThanJournalEntry = entryToUse.IsForTheTipsTab;

                if ( entryToUse.IsForTheTipsTab )
                {
                    if ( GameSettings.Current.GetBoolBySetting( "CenterScreenBannerForTips", true ) )
                        CenterScreenPopupData.CreateAndLogNewOrExtendExistingAndReplaceText( "<color=#ffba36>新游戏提示可用：</color> " + entryToUse.SidebarText, entryToUse.InternalName, 3f );
                }

                bool isfirsttime = entryToUse.GetIsAlreadyLoggedInCurrentCampaign();

                // we're doing this in a gamecommand, so it will be consistent for everyone...
                // unless someone has borked local xml compared to everyone else.  But we can't control everything.
                World_AIW2.Instance.JournalHistory.Add( entryWithData );

                if ( isfirsttime )
                    ArcenExternalCodeHook.Invoke("OnJournalFirstQueued", entryWithData, entryToUse, null, context);

                ArcenExternalCodeHook.Invoke("OnJournalQueued", entryWithData, entryToUse, null, context);
                
                // now write chat text if there is any...
                // but since that's a global thing, only do it on the host
                if ( ArcenNetworkAuthority.GetIsHostMode() && 
                     !World_AIW2.Instance.GetIsTutorial() )
                {
                    if (!string.IsNullOrEmpty(entryToUse.ChatText))
                    {
                        // do any text replacements that we need to.
                        string finalChatText = entryToUse.DoLocalTextReplacements( entryWithData, entryToUse.ChatText );
                        
                        // if we still have text, send it out as a chat message to all the players
                        if (!string.IsNullOrEmpty(finalChatText))
                        {
                            var handler = ChatClickHandler.CreateNewAs<JournalOrTipChatHandler>( "JournalOrTip" );
                            if ( handler != null )
                                handler.String = entryWithData.UniqueID;
                            
                            string prefix = "<color=#3BF6D7>新日志条目：</color> ";
                            if ( entryToUse.IsForTheTipsTab )
                                prefix = "<color=#ffba36>新提示：</color> ";
                            
                            World_AIW2.Instance.QueueChatMessageOrCommand( prefix + finalChatText, ChatType.LogToCentralChat, handler );
                        }
                    }
                }
            }
        }
    }

    /// <summary>
    /// Mark a journal entry as read!
    /// </summary>
    public class GameCommand_JournalEntryMarkedAsRead : BaseGameCommand
    {
        public override void Execute( GameCommand command, ArcenClientOrHostSimContextCore context )
        {
            string uniqueName = command.RelatedString;
            byte playerAccountIDThatReadIt = (byte)command.RelatedIntegers.First;

            JournalEntryInCampaign entry;
            for ( int i = 0; i < World_AIW2.Instance.JournalHistory.Count; i++ )
            {
                entry = World_AIW2.Instance.JournalHistory[i];
                if ( entry.UniqueID == uniqueName )
                    entry.HasBeenViewedByPlayerAccountIDs[playerAccountIDThatReadIt] = true;
            }

        }
    }
}
