import json

filepath = r'D:\Steam\steamapps\common\AI War 2\AIWar2_ChineseTranslation\tools\ilpatch\ArcenAIW2Core.part3.json'

with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Translation dictionary for player-visible strings
translations = {
    "{0}x {1} #{2}": "{0}x {1} #{2}",
    " at (": " 位于 (",
    " rows?": " 行?",
    ": this.MaxHullFinal (": ": this.MaxHullFinal (",
    " * multiplier ": " * 倍率 ",
    ". Ship line ": "。舰船线 ",
    "[null?]": "[null?]",
    "[empty!?]": "[empty!?]",
    "' has a null system at index ": " 在索引处有空系统 ",
    " rather than a system of type ": " 而不是类型为 ",
    " has a system of type ": " 的系统类型为 ",
    " at index ": " 在索引 ",
    " has a system with a DataForMark of ordinal ": " 的系统有 DataForMark 序号为 ",
    " rather than a system of ordinal ": " 而不是序号为 ",
    " has a system with a DataForMark of type ": " 的系统有 DataForMark 类型为 ",
    "\\\\nentity {0} is forbidden because {1}\\\\n": "\\\\n实体 {0} 被禁止，因为 {1}\\\\n",
    "\\\\nentity {0} is not eligible because {1}\\\\n": "\\\\n实体 {0} 不符合条件，因为 {1}\\\\n",
}

# Keys to skip (debug/error/internal identifiers)
skip_keys = {
    # Resource config errors (debug)
    " configured to use resource 1, but no Resource1DisplayName set!",
    " configured to use resource 1, but no Resource1Color set!",
    " configured to use resource 2, but no Resource2Icon set!",
    " configured to use resource 2, but no Resource2DisplayName set!",
    " configured to use resource 2, but no Resource2Color set!",
    " configured to use resource 3, but no Resource3Icon set!",
    " configured to use resource 3, but no Resource3DisplayName set!",
    " configured to use resource 3, but no Resource3Color set!",
    "No GetDoesFactionMatch entry for faction index ",
    # Surrogate table errors (debug)
    "Error: unknown surrogate table '",
    "Error: surrogate table '",
    "' has a null table object on it.",
    "Error: RelatedTable is null on field '",
    "' for faction type '",
    "' when asked for table '",
    "Error: RelatedTableSubset is null on field '",
    "' when asked for table subset '",
    "DoPostAllLoadingFinalLinkingLogic Error: RelatedTable has no way of being set for type '",
    # NPC ship cap error
    "Could not find npc_ship_cap of type '",
    "', which was requested by faction ",
    "Could not find GetMainGameObjectParent!",
    "Could not find AddonObjectOrParticleField Prefab '{0}' for {1}.",
    # Debug identifiers
    "PlanetCentricVisualEffects.CurrentlyDisplayed",
    "WARNING ONLY UNLESS HUGE REPEATS: RapidAntiLeakPoolable expiration for EntitySystemCollection '",
    "' of type ",
    "Null ParentEntity passed to System creation method!",
    "Null EntitySystemTypeData passed to System creation method!",
    "EntitySystem.potentialTargetsToPriorityLookup",
    "System Type: ",
    "Junk A",
    "Junk B",
    "Junk C",
    "Early Deser",
    "Error reading EntitySystem {0} for a {1}. We could not find a CustomSystemType named {2}.",
    # Damage trace lines
    "result *= fuelArgonRatio, new result = ",
    "result *= fuelRadonRatio, new result = ",
    "result *= fuelXenonRatio, new result = ",
    "result *= forCompressedShots, new result = ",
    "result = maxDamageCanTake, new result = ",
    "result = (FInt) limit, new result = ",
    "Tracing GetAttackPowerAgainst for shot from ",
    "Calculating ship-, shiptype-, fleet- and planet-based damage factors, startingMultiplier = ",
    ", bonusDamage = ",
    "result = 0 because we're an ion cannon and the target has too high an albedo or mark level",
    "result = 0 because we're an ion cannon and the target has too high a mark level",
    "ion-insta-kill rule applies, result = (Target.GetMaxShieldPoints()+ Target.GetMaxHullPoints()) * damage = ",
    "result = 0 because we want to devour, but the food is too high mark or too massive.",
    "Devour-insta-kill rule applies, result = (Target.GetMaxShieldPoints()+ Target.GetMaxHullPoints()) = ",
    "Factoring in ",
    " multiplier because target is tractored. New startingMultiplier ",
    " flat damage due to damage amplification. New flatDamageIncrease = ",
    " damage multiplier due to damage amplification. New startingMultiplier = ",
    " additional damage percentage per consumed weapon point, consumed weapon point count is ",
    ". New multiplier ",
    " additional damage percentage per current weapon point, current weapon point count is ",
    "startingMultiplier *= myTData.DamageModifierWhileUnderForcefield = ",
    "(baseShotDamage + bonusDamage) * multiplier = result; ({0}+{1})*{2:0.0} = {3:0.0}",
    "result = myTData.OutgoingDamageModifiers_Everything[",
    "].ApplyIfMeetCriterias( parent, Target, result ) = ",
    "result = targetTData.IncomingDamageModifiers_Everything[",
    "].ApplyIfMeetCriterias( Target, parent, result ) = ",
    "result = targetShipClassData.ModifyShotDamage( TypeData.GetAmmoTypeOrNull(), result ) = ",
    "Tracing GetEnemyEntitiesIntersectingInstaFireShot",
    # Trace fragments
    "How could we not find a typeData from ",
    # Ship/fleet debug
    "FleetMem.TypeData",
    "Tried to call GetSmallestExistingStackToAddToOnSamePlanetAsFleetLeader_YesTransporting on a fleet not in transport mode.",
    "Tried to call GetSmallestExistingStackToAddToOnSamePlanetAsFleetLeader_NotTransporting on a fleet in transport mode.",
    "TransportContents.Count",
    "Fleet Membership KillAllEntitiesWithinBecauseInvalid",
    "Fleet Membership ClearEntities",
    "GameEntityTypeData_Variant_Table.AllocVariantShipType called for {0}+{1} {2}",
    "TryCreateVariant.newTypeInternalName",
    "New Type ID: ",
    "Adding variant: ",
    "GameEntityTypeData_Variant_Table.DeallocVariantShipType called for {0}",
    "\\tEnabled Summoner Tags is null",
    "\\tNo Summoner Tags",
    "\\tChecking for summoner tag ",
    ". Enabled tag:  ",
    ". of ",
    "How could we not find a mark 1 for ",
    "Tried to compost the fake entity!  Something has gone very wrong...",
    # Entity creation errors
    "GameEntity_Squad was passed a null GameEntityTypeData!",
    "GameEntity_Squad was passed a null Planet!",
    "Perm: Init Error! ",
    " has a null system at index ",
    "Fake Entity",
    " Tried to create an entity that was already in the central registry! ",
    ".  Corrected to a fresh ID for now, but calling code should also be corrected to not do this.  ID reuse that hits the central registry, even for transformation of units, leads to sim confusion.  Either fix it to be resurrection-ready, or fix the calling code to not reuse the ID.  Original squad type is: ",
    " Tried to create an entity that was already marked as dead, and not marked for resurrection! ",
    ".  Corrected to a fresh ID for now, but calling code should also be corrected to not do this.  ID reuse that hits the central registry, even for transformation of units, leads to sim confusion.  Either fix it to wait for resurrection, or fix the calling code to not reuse the ID.  Original squad removal message was: ",
    "Faction was passed in as null to CreateNewWithExistingID!",
    "Oi!  Tried to CreateNewWithExistingID over the FakeEntity!",
    "Post Creation Latent Fix A",
    "Post Creation Latent Fix B",
    "Helper_PostCreationOfSquad Error (AND DID TRY TO FIX IT!?): wanted faction ",
    ", but got ",
    " instead.",
    "Helper_PostCreationOfSquad Error (but did not try to fix it?): wanted faction ",
    "Helper_PostCreationOfSquad Error: wanted planet ",
    "Helper_PostCreationOfSquad Error: wanted type ",
    "Fixed typedata ",
    "Post-fix typedata ",
    "Fixed dataForMark ",
    "Post-fix dataForMark ",
    "D:\\vclarge\\AI_War_2_Ultra\\CodeMain\\ArcenAIW2Core\\src\\Logic\\GameState\\GameEntity\\GameEntity_Squad.cs",
    "Error! GameEntity.CreateNew() is a fleet leader of an unknown type and could not be added properly (",
    "Error! GameEntity.CreateNew() passed null FleetOrNullIfNotShip for an entity of category Ship, and no loose fleet found: ",
    "Error during CreateNew on squad, result.FleetMembership was still null for type ",
    " after GetOrAddMembershipGroupBasedOnSquadType_WithUniqueIDForDuplicate()",
    "Error! GameEntity.CreateNew() tried to add a non-ship entity ",
    " to a MembershipOrNullIfNotShip: ",
    "Error during CreateNew on squad, FleetMembership was never set for type ",
    ", GetIsFleetLeader(): ",
    ", skipNormalFleetMembershipAdditions: ",
    ", FleetOrNullIfNotShip: ",
    "Post Creation - Go To Parent",
    "Error!  Only found ",
    " angles to distribute ",
    " orbiters around a ",
    "Error during CreateNew on squad, debugPoint ",
    # Deserialize/debug identifiers
    "GameEntity_Squad Deser",
    "GuardedUnit.PrimaryKeyID",
    "GroupMoveSpeed.SpeedGroupID",
    "More Squad Stuff",
    "GuardOrPatrolOffsetPoint.X",
    "GuardOrPatrolOffsetPoint.Y",
    "AIReinforcementPoint.CountInside",
    "AIReinforcementPointReasonCodesForDebugging.ReasonCode",
    "AIReinforcementPointReasonCodesForDebugging.CountInside",
    "ExoGalacticAttackTarget.PrimaryKeyID",
    "Squad Deser",
    "Squad Outer",
    "Oi!  Tried to FinishDeserializeFrom over the FakeEntity!",
    "Oi!  Tried to DeserializedIntoSelf over the FakeEntity!",
    "Squad Systems",
    "Systems.Count",
    "Perm: Deser Error! ",
    " systems, but instead has ",
    "GuardOrPatrolOffsetPoints.Count",
    "ProtectingShields_ReduceDamage.Count",
    "ProtectingShields_NoDamageReduction.Count",
    "FramePlan_Protection_NextFrameProtectingShields.Count",
    "AIReinforcementPointContents.Count",
    "AIReinforcementPointReasonCodesForDebugging.Count",
    "DeathEffectDamageLastDoneByFactionIndex.Count",
    "DeathEffectCausingDamageReceivedToEntity.Count",
    "ShipGrantsList.Count",
    "Tossing ChangeAmount",
    # BaseInfo/DeepInfo debug
    "Squad BaseInfo",
    "Squad BaseInfo Source",
    "Squad DeepInfo",
    "Squad DeepInfo Source",
    "Error!  Called CreateExternalBaseInfo() on squad with null BaseInfoSource: ",
    "Error!  Called CreateExternalBaseInfo() on squad with desired BaseInfoSource '",
    "' when the squad already had a BaseInfoSource of type '",
    "Warning A!  Called CreateExternalBaseInfo<",
    ">() when BaseInfo was actually a different type, ",
    ". It has existed for ",
    "Error!  Could not find ExternalSquadBaseInfo entry with name: ",
    "Error B!  Called CreateExternalBaseInfo<",
    "Error!  Called CreateExternalDeepInfo() on squad with null DeepInfoSource: ",
    "Error!  Called CreateExternalDeepInfo() on squad with desired DeepInfoSource '",
    "' when the squad already had a DeepInfoSource of type '",
    "Error A!  Called CreateExternalDeepInfo<",
    "Error!  Could not find ExternalSquadDeepInfo entry with name: ",
    "Error B!  Called CreateExternalDeepInfo<",
    "Error!  Called Squad.GetExternalBaseInfoAs<{0}>() when BaseInfo was null on {1}\\n{2}",
    "Error!  Called GetExternalBaseInfoAs<",
    "[null fmem]",
    "[null fleet]",
    "Error!  Called GetFactionBaseInfoOrNullAs_Safe<",
    ">() when BaseInfo was null for the faction ",
    "Error!  Called GetFactionDeepInfoOrNullAs_Safe<",
    ">() when DeepInfo was null for the faction ",
    # DataForMark errors
    "Error! DataForMark is null on entity ",
    " with desired mark level of ",
    "Error! DataForMark is null on system ",
    " could not find any between ",
    "Perm: Error! ",
    " is not fleet leader of of fleet ",
    ", but instead another ship ",
    " is.  Deleting self to fix.",
    # Debug trace lines
    "{0}.DoEntityStepLogic_Ship selfbuildingmetalremaining {1} and secondsspentasremains {2} so returning",
    "{0} has order GetIntoTransport to {1} on {2} planet {3} and {4}",
    "{0}.TryToPutMeIntoTargetTransport_HostOnly returned {1}",
    "Fixing To Be With Parent",
    "tried to give orbiter order to attack target of parent system but failed\\n",
    "Error!  Could not find any units with the tag '{0}' to spawn as a child of {1}.",
    "{0} produced child {1}: start behavior is {2}, current behavior is {3} and copyParentBehavior is {4}.",
    "{0}.RemoveInvalidatedOrdersAndReturnFirstValid_ThatIsNotDecollision is clearing order {1} because {2}",
    "{0}.RemoveInvalidatedOrdersAndReturnFirstValid_IncludingDecollision is clearing order {1} because {2}",
    # Debug strength/reinforcement
    "GetStrengthPerSquad: A ",
    "GetStrengthPerSquad: B ",
    "GetStrengthPerSquad: C ",
    "There was an attempt to have ",
    " as reinforcement.  Reduced to 10,000 instead.",
    # Damage trace fragments
    ">TakeDamageDirectly; DamageAmount = ",
    "return early because DamageAmount == 0",
    "return early because this.TypeData.ImmuneToAllDamage && Damage == DamageSource.SomeSortOfEnemy",
    "return early because this.TypeData.ImmuneToAllDamageFromPlayersInvisibly && Damage == DamageSource.SomeSortOfEnemy",
    "return early because this.TypeData.ImmuneToAllDamageForSecondsAfterCreation > this.GetSecondsSinceCreation() && Damage == DamageSource.SomeSortOfEnemy",
    "return early because this.CountOfEntitiesProvidingExternalInvulnerability >= ",
    " && Damage == DamageSource.SomeSortOfEnemy",
    "return early because this.ToBeRemovedAtEndOfThisFrame || this.HasBeenRemovedFromSim",
    "DamageAmount += firingSystemParentOrNull.CalculatedAddedDamage = ",
    "DamageAmount *= ActualShotsHitting= ",
    "\\nShot Compression Stats: ActualHitEvents: ",
    ", CompressedShots: ",
    ", MaxStacksAllowedToKill: ",
    "return early because this.Debug_IgnoresDamage",
    "return early because HonorFiniteHitCountAOE && Context.WorkingAOETargetsThatHaveBeenHitList.Contains( this )",
    "DamageAmount *= ExternalConstants.Instance.Balance_BonusDamageForUnderConstruction = ",
    " Applying the full damage as corrosion",
    " then setting Damage to 0 so as to not do anything else",
    "because FiringSystemOrNull.TypeData.OverdrivesShields, DamageAmount = ",
    "DamageAmount -= (DamageAmount * FiringSystemOrNull.DataForMark.PercentDamageBypassesPersonalShields).IntValue = ",
    "because of TypeData.ShipClass.ModifyExoticDamage(ShipClassData_ExoticDamageType.RevengeShot, DamageAmount) ",
    " DamageAmount = ",
    "damageToShields = DamageAmount = ",
    "damageToShields = FiringSystemOrNull.TypeData.OutgoingDamageModifiers_PersonalShieldsAndAllShields[",
    "].ApplyIfMeetCriterias( firingSystemParentOrNull, this, damageToShields ) = ",
    "damageToShields = this.TypeData.IncomingDamageModifiers_PersonalShieldsAndAllShields[",
    "].ApplyIfMeetCriterias( this, firingSystemParentOrNull, damageToShields ) = ",
    "because damageToShields > currentShieldHealth, damageToShields = currentShieldHealth = ",
    "DamageAmount -= damageToShields = ",
    "shield drain restored to attacker = ",
    "returning now because early because OnlyDamageShieldNotHull",
    "DamageAmount += damageToSkipShields = ",
    "DamageAmount = FiringSystemOrNull.TypeData.OutgoingDamageModifiers_HullOnly[",
    "].ApplyIfMeetCriterias( firingSystemParentOrNull, this, DamageAmount ) = ",
    "DamageAmount = this.TypeData.IncomingDamageModifiers_HullOnly[",
    "].ApplyIfMeetCriterias( this, firingSystemParentOrNull, DamageAmount ) = ",
    "because DamageAmount > currentHealth, DamageAmount = currentHealth = ",
    " ; OverkillDamage = ",
    "numExtraStacksKilled = OverkillDamage / totalUnitHealth = ( ",
    "numExtraStacksKilled = MaxStacksAllowedToKill - 1 = ",
    "numExtraStacksKilled = ExtraStackedSquadsInThis = ",
    "Killing all ",
    " ships in stack",
    " ships out of ",
    " damage to the next unit in the stack because it only killed ",
    " out of ",
    " so far",
    "Remaining stacks, hull / shield: ",
    ", actual damage done: ",
    "FleetMetrics OnFleetDamage error: ",
    "exception in ApplyDebuffs at debugstage {0}\\n{1}",
    "splitstack; this.ChargeAmounts.Length={0} newSquad.ChargeAmounts.Length={1} and expected <=",
    "splitstack; this.ChargeAmounts.Length={0} this.TypeData.ChargeTypes.Count={1} and >=",
    "exception at debugstage {0}\\n{1}",
    "DoOnDestructionLogic for {0}",
    "mem is {0} fleet is {1} centerpiece is {2}",
    "FleetMetrics OnFleetKill/Lost error: ",
}

translated_count = 0
skipped_count = 0

for key, val in list(data.items()):
    if val != '':
        continue
    
    if key in translations:
        data[key] = translations[key]
        translated_count += 1
    elif key in skip_keys:
        skipped_count += 1
    else:
        # Default: skip (better to leave untranslated than guess)
        skipped_count += 1
        print(f"UNCATEGORIZED: {repr(key)}")

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Translated: {translated_count}")
print(f"Skipped (non-translatable): {skipped_count}")
print(f"Total empty processed: {translated_count + skipped_count}")