param(
    [string]$SourceBase = "D:\Steam\steamapps\common\AI War 2\XMLMods",
    [string]$TargetBase = "D:\Steam\steamapps\common\AI War 2\AIWar2_ChineseTranslation\XMLMods"
)

function Translate-Text {
    param([string]$text)
    if ([string]::IsNullOrEmpty($text)) { return $text }
    if ($text -cmatch '^[A-Z0-9_.\s/-]+$' -and $text.Length -gt 3) { return $text }
    
    $r = $text
    
    # === Phrase-level (longest first) ===
    # AIShieldGenerators
    $r = $r -replace 'AI Shield Generator \(Network 1\)', 'AI护盾发生器（网络1）'
    $r = $r -replace 'AI Shield Generator \(Network 2\)', 'AI护盾发生器（网络2）'
    $r = $r -replace 'AI Shield Generator \(Network 3\)', 'AI护盾发生器（网络3）'
    $r = $r -replace 'AI Shield Generator', 'AI护盾发生器'
    $r = $r -replace 'AI Core Shield', 'AI核心护盾'
    $r = $r -replace 'Core Shield', '核心护盾'
    $r = $r -replace 'Sabotage Shield Generator', '破坏护盾发生器'
    $r = $r -replace 'Base Number of Shield Generators', '护盾发生器基础数量'
    $r = $r -replace 'Maximum Additional Shield Generators', '护盾发生器最大额外数量'
    $r = $r -replace 'Shield Generator Network Stability', '护盾发生器网络稳定性'
    
    # DarkSphere
    $r = $r -replace 'Dark Command Station', '黑暗指挥站'
    $r = $r -replace 'Dark Cmd', '黑暗指挥站'
    $r = $r -replace 'Dark Gatling', '黑暗加特林'
    $r = $r -replace 'Dark Cannon', '黑暗加农炮'
    $r = $r -replace 'Anicca the Mercy of Entropy', '阿尼卡——熵之慈悲'
    $r = $r -replace 'Drone Perimeter', '无人机周界'
    $r = $r -replace 'Recover Corrupted Schematic', '恢复受损蓝图'
    $r = $r -replace 'Aquire this schematic for our fleet\?', '为舰队获取此蓝图？'
    $r = $r -replace 'Aquire this schematic for our defenses\?', '为防御系统获取此蓝图？'
    
    # Leere
    $r = $r -replace 'Enable the Leere', '启用戾尔'
    $r = $r -replace 'Leere Rivalry', '戾尔竞争'
    $r = $r -replace 'Leere Aura', '戾尔光环'
    $r = $r -replace 'Knallen Spawn Timer', '克纳伦生成计时器'
    $r = $r -replace 'First Spawn Timer', '首次生成计时器'
    $r = $r -replace 'Cooldown Timer', '冷却计时器'
    $r = $r -replace 'Knallen Bomb', '克纳伦炸弹'
    
    # AMU Settings
    $r = $r -replace 'Enable Auto-Juggle Energy Assistant', '启用自动调整能源助手'
    $r = $r -replace 'Auto-Determine Energy Count', '自动确定能源数量'
    $r = $r -replace 'Target Energy While In Brownout', '低电力时目标能源'
    $r = $r -replace 'Target Energy', '目标能源'
    $r = $r -replace 'Always Show Notification', '始终显示通知'
    $r = $r -replace 'Execute Per Sim-Step', '每模拟步执行'
    $r = $r -replace 'Enable Experimental Defense Autobuilding', '启用实验性防御自动建造'
    $r = $r -replace 'Enable Capturable Repositioning', '启用可占领物重定位'
    $r = $r -replace 'Minimum Gravwell Distance', '最小重力井距离'
    $r = $r -replace 'Maximum Gravwell Distance', '最大重力井距离'
    $r = $r -replace 'Minimum Wormhole Distance', '最小虫洞距离'
    $r = $r -replace 'Reposition Asteroid Mines', '重定位小行星矿场'
    
    # Mod meta
    $r = $r -replace 'Settings related to the Leere mod\.', '与戾尔模组相关的设置。'
    $r = $r -replace 'Enable different features of the Leere mod\.', '启用戾尔模组的不同功能。'
    $r = $r -replace 'Configure different features of the Leere mod\.', '配置戾尔模组的不同功能。'
    $r = $r -replace 'Shows the strength of all active Leere Auras on the map, as well as the currently active Aura, if any, appended onto each Planet', '在地图上显示所有活跃戾尔光环的强度，以及当前活跃光环（如有）附加在每个行星'
    
    # MSD AutoBuild
    $r = $r -replace 'Auto Build Gorgon Frigates', '自动建造戈耳工护卫舰'
    $r = $r -replace 'Auto Build Escort Carriers', '自动建造护航航母'
    $r = $r -replace 'Auto Build Ambush Carriers', '自动建造伏击航母'
    $r = $r -replace 'Auto Build Flypaper Frigates', '自动建造粘蝇纸护卫舰'
    $r = $r -replace 'Auto Build Artillery Destroyers', '自动建造火炮驱逐舰'
    $r = $r -replace 'Auto Build Cruise Missile Batteries', '自动建造巡航导弹炮台'
    
    # MSD Entity names
    $r = $r -replace 'Stormfront Ark', '风暴前哨方舟'
    $r = $r -replace 'Ballistic Vortex', '弹道涡旋'
    $r = $r -replace 'Heavy Shrike Launchers', '重型伯劳发射器'
    $r = $r -replace 'Escort Vanguard Drone', '护航先锋无人机'
    $r = $r -replace 'Lesser Shotgun Acid Cannon', '次级霰弹酸液炮'
    $r = $r -replace 'Vanguard Drones', '先锋无人机'
    $r = $r -replace 'Viper Corvette', '毒蛇护卫舰'
    $r = $r -replace 'Viper Twin Repeater', '毒蛇双联速射炮'
    $r = $r -replace 'Eradicator Laser Cannon', '歼灭激光炮'
    $r = $r -replace 'Shockwave Cruise Missile', '冲击波巡航导弹'
    $r = $r -replace 'Nova Burst Cruise Missile', '新星爆裂巡航导弹'
    $r = $r -replace 'Stormfront MIRV', '风暴前哨多弹头导弹'
    $r = $r -replace 'Stormfront Raid Frigate', '风暴前哨突击护卫舰'
    $r = $r -replace 'Mini-Nucleophilic Cannon', '迷你亲核加农炮'
    $r = $r -replace 'Heavy Shrike Missiles', '重型伯劳导弹'
    $r = $r -replace 'Shrike Missiles', '伯劳导弹'
    $r = $r -replace 'Cloaking Device', '隐形装置'
    $r = $r -replace 'Gorgon Aggregate Body Frigate', '戈耳工聚合体护卫舰'
    $r = $r -replace 'Gorgon Paralysis Beam', '戈耳工麻痹光束'
    $r = $r -replace 'Viper Twin Repeater Banks', '毒蛇双联速射炮组'
    $r = $r -replace 'Station-Keeping Gorgon', '驻防戈耳工'
    $r = $r -replace 'Station-Keeping Escort Carrier', '驻防护航航母'
    $r = $r -replace 'Station-Keeping Ambush Carrier', '驻防伏击航母'
    $r = $r -replace 'Station-Keeping Artillery', '驻防火炮'
    $r = $r -replace 'Flypaper Frigate', '粘蝇纸护卫舰'
    $r = $r -replace 'Charged Shells', '充能弹'
    $r = $r -replace 'Electrical Overload Emitter', '电气过载发射器'
    $r = $r -replace 'Tractor Beam', '牵引光束'
    $r = $r -replace 'Artillery Destroyer', '火炮驱逐舰'
    $r = $r -replace 'Twinned Magnetic Accelerator', '双联磁力加速器'
    $r = $r -replace 'Suppressive Flak', '压制防空炮'
    $r = $r -replace 'Augmented Artillery', '增强型火炮'
    $r = $r -replace 'Briar Patch', '荆棘陷阱'
    $r = $r -replace 'Briar Thorns', '荆棘刺'
    $r = $r -replace 'Screamer Heavy Rockets', '尖叫重型火箭'
    $r = $r -replace 'Screamer Rockets Pod', '尖叫火箭巢'
    $r = $r -replace 'Screamer Micro-Fusion Rockets', '尖叫微型聚变火箭'
    $r = $r -replace 'Bomb-Pumped Laser Minefield', '泵浦激光雷区'
    $r = $r -replace 'Bomb-Pumped Laser', '泵浦激光'
    $r = $r -replace 'Cruise Missile Battery', '巡航导弹炮台'
    $r = $r -replace 'Shockwave Missile Launcher', '冲击波导弹发射器'
    $r = $r -replace 'Nova Burst Missile Launcher', '新星爆裂导弹发射器'
    $r = $r -replace 'Fortified AI Cruise Missile Base', '强化AI巡航导弹基地'
    $r = $r -replace 'AI Shockwave Missile Installation', 'AI冲击波导弹设施'
    $r = $r -replace 'Warhead Deployment', '飞弹部署'
    $r = $r -replace 'Warhead Detonation', '飞弹引爆'
    $r = $r -replace 'Parasitic Flakburst Cannon', '寄生高爆炮'
    $r = $r -replace 'Escort Carrier', '护航航母'
    $r = $r -replace 'Escort Vanguard', '护航先锋'
    
    # KaizersMarauders
    $r = $r -replace 'Kaizers Marauders', '凯泽掠夺者'
    $r = $r -replace 'Needle Interceptor', '飞针拦截机'
    $r = $r -replace 'Needle Impactor', '飞针撞击炮'
    $r = $r -replace 'Plated Needle', '镀层飞针'
    $r = $r -replace 'Armored Needle', '装甲飞针'
    $r = $r -replace 'Mortar Heavy Corvette', '迫击炮重型护卫舰'
    $r = $r -replace 'Guard Mortar', '守卫迫击炮'
    $r = $r -replace 'Protector Mortar', '保护者迫击炮'
    $r = $r -replace 'Sting Light Frigate', '螫刺轻型护卫舰'
    $r = $r -replace 'Shield Sting', '护盾螫刺'
    $r = $r -replace 'Cloaked Sting', '隐形螫刺'
    $r = $r -replace 'Mercurial Sting', '汞变螫刺'
    $r = $r -replace 'Silenced Shield Sting', '静音护盾螫刺'
    $r = $r -replace 'Torpedo Bomber', '鱼雷轰炸机'
    $r = $r -replace 'Seismic Torpoedo', '地震鱼雷'
    $r = $r -replace 'Strike Torpedo', '突击鱼雷'
    $r = $r -replace 'Blitz Torpedo', '闪击鱼雷'
    $r = $r -replace 'Disrupter Corvette', '干扰者护卫舰'
    $r = $r -replace 'Goo Canon', '粘液炮'
    $r = $r -replace 'Plated Disrupter', '镀层干扰者'
    $r = $r -replace 'Armored Disrupter', '装甲干扰者'
    $r = $r -replace 'Rampage Frigate', '狂怒护卫舰'
    $r = $r -replace 'Impactor Cannon', '撞击加农炮'
    $r = $r -replace 'Deploy MLRS Missiles', '部署多管火箭导弹'
    $r = $r -replace 'Killer Rampage', '杀手狂怒'
    $r = $r -replace 'Death Rampage', '死亡狂怒'
    $r = $r -replace 'Explosive Finale', '爆炸终曲'
    $r = $r -replace 'MLRS Missile', '多管火箭导弹'
    $r = $r -replace 'Release Missiles', '释放导弹'
    $r = $r -replace 'Killer MLRS', '杀手多管火箭'
    $r = $r -replace 'Death MLRS', '死亡多管火箭'
    $r = $r -replace 'Hunter-Fighter', '猎人战斗机'
    $r = $r -replace 'Dematerializer', '解物质器'
    $r = $r -replace 'Cloaked Hunter', '隐形猎人'
    $r = $r -replace 'Mercurial Hunter', '汞变猎人'
    $r = $r -replace 'Silenced Dematerializer', '静音解物质器'
    $r = $r -replace 'Acidic Light Corvette', '酸性轻型护卫舰'
    $r = $r -replace 'Acid Spreader', '酸液散布器'
    $r = $r -replace 'Strike Acidic', '突击酸性'
    $r = $r -replace 'Blitz Acidic', '闪击酸性'
    $r = $r -replace 'Bulk Heavy Frigate', '堡垒重型护卫舰'
    $r = $r -replace 'Matter Transfer', '物质传输'
    $r = $r -replace 'Tachyon Array', '快子阵列'
    $r = $r -replace 'Guard Bulk', '守卫堡垒'
    $r = $r -replace 'Protector Bulk', '保护者堡垒'
    $r = $r -replace 'Lightshow Cruiser', '光秀巡洋舰'
    $r = $r -replace 'Heavy Beam', '重型光束'
    $r = $r -replace 'Pinpoint Beam', '精准光束'
    $r = $r -replace 'Killer Lightshow', '杀手光秀'
    $r = $r -replace 'Death Lightshow', '死亡光秀'
    
    # LostHumans
    $r = $r -replace 'Lost Human', '失落人类'
    $r = $r -replace 'Assault Frigate', '突击护卫舰'
    $r = $r -replace 'Militia Carrier', '民兵航母'
    $r = $r -replace 'Derelict Miner', '废弃采矿船'
    $r = $r -replace 'Derelict Constructor', '废弃工程船'
    $r = $r -replace 'Derelict Engineer Frigate', '废弃工程师护卫舰'
    $r = $r -replace 'Human Colony', '人类殖民地'
    $r = $r -replace 'Captured Human Colony', '被俘人类殖民地'
    $r = $r -replace 'Lost Human Rogue', '失落人类浪客'
    $r = $r -replace 'Rogue Guild', '浪客公会'
    $r = $r -replace 'Rogue Firewall', '浪客防火墙'
    $r = $r -replace 'Fortified Scourge Lab', '强化天灾实验室'
    $r = $r -replace 'Fortress Fusion Rockets', '堡垒聚变火箭'
    $r = $r -replace 'Fortress Energy Wave', '堡垒能量波'
    $r = $r -replace 'Construction Convoy', '建造护航队'
    $r = $r -replace 'Scourge Lab', '天灾实验室'
    $r = $r -replace 'Lost Colonies', '失落殖民地'
    $r = $r -replace 'Scourge Labs', '天灾实验室'
    $r = $r -replace 'Travelers', '旅行者'
    $r = $r -replace 'Rogues', '浪客'
    
    # SKCivilianIndustry
    $r = $r -replace 'Civilian Industry', '民用工业'
    $r = $r -replace 'Grand Station', '中央站'
    $r = $r -replace 'Trade Station', '贸易站'
    $r = $r -replace 'Trade Post', '贸易哨站'
    $r = $r -replace 'Cargo Ship', '货船'
    $r = $r -replace 'Militia Construction Ship', '民兵工程船'
    $r = $r -replace 'Militia Outpost', '民兵前哨'
    $r = $r -replace 'Militia Patrol Post', '民兵巡逻哨站'
    $r = $r -replace 'Advanced Civilian Shipyard', '高级民用船坞'
    $r = $r -replace 'Militia Headquarters', '民兵总部'
    $r = $r -replace 'Militia Protector Shipyards', '民兵保护者船坞'
    $r = $r -replace 'Militia Barracks', '民兵兵营'
    $r = $r -replace 'Civilian Sniper', '民用狙击手'
    $r = $r -replace 'Civilian Raptor', '民用猛禽'
    $r = $r -replace 'Civilian Ambush Turret', '民用伏击炮塔'
    $r = $r -replace 'Cracker Jack Protector', '巧手保护者'
    $r = $r -replace 'Cracker Bolt', '巧手弹'
    $r = $r -replace 'Engine Jacker', '引擎劫持器'
    $r = $r -replace 'Civilian Concussion Corvette', '民用震荡护卫舰'
    $r = $r -replace 'Civilian Siege Frigate', '民用攻城护卫舰'
    $r = $r -replace 'Civilian Concussion Turret', '民用震荡炮塔'
    $r = $r -replace 'Thunderstrike Protector', '雷霆打击保护者'
    $r = $r -replace 'Thunder Torpedo', '雷霆鱼雷'
    $r = $r -replace 'Civilian Pike Corvette', '民用长矛护卫舰'
    $r = $r -replace 'Civilian Agravic Pod', '民用反重力舱'
    $r = $r -replace 'Civilian Pike Turret', '民用长矛炮塔'
    $r = $r -replace 'Paladin Protector', '圣骑士保护者'
    $r = $r -replace 'Siphon Suppression Gatling', '虹吸压制加特林'
    $r = $r -replace 'Civilian Pulsar Tank', '民用脉冲坦克'
    $r = $r -replace 'Civilian Assault Frigate', '民用突击护卫舰'
    $r = $r -replace 'Civilian MLRS Turret', '民用多管火箭炮塔'
    $r = $r -replace 'Brick Breaker Protector', '碎砖者保护者'
    $r = $r -replace 'Brick Bomb', '砖头炸弹'
    $r = $r -replace 'Civilian V-Wing', '民用V翼'
    $r = $r -replace 'Civilian Autocannon Minipod', '民用机炮迷你舱'
    $r = $r -replace 'Civilian Tritium Sniper Turret', '民用氚狙击炮塔'
    $r = $r -replace 'Hurricane Protector', '飓风保护者'
    $r = $r -replace 'Hurricane Railcannon', '飓风轨道炮'
    $r = $r -replace 'Storm Core', '风暴核心'
    $r = $r -replace 'Civilian Vampire Claw', '民用吸血鬼之爪'
    $r = $r -replace 'Civilian Metabolizing Gangsaw', '民用代谢链锯'
    $r = $r -replace 'Civilian Kinetic Spike Turret', '民用动能尖刺炮塔'
    $r = $r -replace 'Kinetic Spike', '动能尖刺'
    $r = $r -replace 'Excalibur Protector', '圣剑保护者'
    $r = $r -replace 'Ranged Blade', '远程剑刃'
    $r = $r -replace 'Tractor Blade', '牵引刀刃'
    $r = $r -replace 'Civilian Raider', '民用突击者'
    $r = $r -replace 'Civilian Raid Frigate', '民用突袭护卫舰'
    $r = $r -replace 'Civilian Blitz Cannon Turret', '民用闪击加农炮塔'
    $r = $r -replace 'Blitz Cannon', '闪击加农炮'
    $r = $r -replace 'Grim Reaper Protector', '死神保护者'
    $r = $r -replace 'Reaper Bolt', '死神弹'
    $r = $r -replace 'Civilian Inhibiting Tesla Corvette', '民用抑制特斯拉护卫舰'
    $r = $r -replace 'Civilian Grenade Launcher Corvette', '民用榴弹发射器护卫舰'
    $r = $r -replace 'Civilian Fortified Tesla Turret', '民用强化特斯拉炮塔'
    $r = $r -replace 'Wildfire Protector', '野火保护者'
    $r = $r -replace 'Flak Grenade', '防空手榴弹'
    $r = $r -replace 'Civilian Spider', '民用蜘蛛'
    $r = $r -replace 'Civilian Warbird Frigate', '民用战鸟护卫舰'
    $r = $r -replace 'Civilian Spider Turret', '民用蜘蛛炮塔'
    $r = $r -replace 'Tangler Protector', '缠绕者保护者'
    $r = $r -replace 'Vine Piercer', '藤蔓穿刺者'
    $r = $r -replace 'Vine Sprayer', '藤蔓喷洒器'
    $r = $r -replace 'Civilian Sentinel Gunboat', '民用哨兵炮艇'
    $r = $r -replace 'Civilian Etherjet', '民用以太喷射机'
    $r = $r -replace 'Civilian Techno Babble Turret', '民用技术胡话炮塔'
    $r = $r -replace 'Plinker Cannon', '碰碰加农炮'
    $r = $r -replace 'Orchestrator Protector', '指挥家保护者'
    $r = $r -replace 'Orchestration Array', '指挥阵列'
    $r = $r -replace 'Tachyon Array', '快子阵列'
    
    # === Generic word-level ===
    $r = $r -replace '(?<![a-zA-Z])Frigate(?![a-zA-Z])', '护卫舰'
    $r = $r -replace '(?<![a-zA-Z])Flagship(?![a-zA-Z])', '旗舰'
    $r = $r -replace '(?<![a-zA-Z])Turret(?![a-zA-Z])', '炮塔'
    $r = $r -replace '(?<![a-zA-Z])Guardian(?![a-zA-Z])', '守护者'
    $r = $r -replace '(?<![a-zA-Z])Bomber(?![a-zA-Z])', '轰炸机'
    $r = $r -replace '(?<![a-zA-Z])Fighter(?![a-zA-Z])', '战斗机'
    $r = $r -replace '(?<![a-zA-Z])Carrier(?![a-zA-Z])', '航母'
    $r = $r -replace '(?<![a-zA-Z])Destroyer(?![a-zA-Z])', '驱逐舰'
    $r = $r -replace '(?<![a-zA-Z])Cruiser(?![a-zA-Z])', '巡洋舰'
    $r = $r -replace '(?<![a-zA-Z])Battleship(?![a-zA-Z])', '战列舰'
    $r = $r -replace '(?<![a-zA-Z])Dreadnought(?![a-zA-Z])', '无畏舰'
    $r = $r -replace '(?<![a-zA-Z])Missile(?![a-zA-Z])', '导弹'
    $r = $r -replace '(?<![a-zA-Z])Warhead(?![a-zA-Z])', '飞弹'
    $r = $r -replace '(?<![a-zA-Z])Torpedo(?![a-zA-Z])', '鱼雷'
    $r = $r -replace '(?<![a-zA-Z])Interceptor(?![a-zA-Z])', '拦截机'
    $r = $r -replace '(?<![a-zA-Z])Strikecraft', '星战'
    $r = $r -replace 'Strike Craft', '星战'
    $r = $r -replace '(?<![a-zA-Z])Marauders', '掠夺者'
    $r = $r -replace '(?<![a-zA-Z])Marauder(?![a-zA-Z])', '掠夺者'
    $r = $r -replace '(?<![a-zA-Z])Drone(?![a-zA-Z])', '无人机'
    $r = $r -replace '(?<![a-zA-Z])Drones(?![a-zA-Z])', '无人机'
    $r = $r -replace '(?<![a-zA-Z])Shield(?!ing)', '护盾'
    $r = $r -replace '(?<![a-zA-Z])Cannon(?![a-zA-Z])', '加农炮'
    $r = $r -replace '(?<![a-zA-Z])Laser(?![a-zA-Z])', '激光'
    $r = $r -replace '(?<![a-zA-Z])Rocket(?![a-zA-Z])', '火箭'
    $r = $r -replace '(?<![a-zA-Z])Beam(?!\w)', '光束'
    $r = $r -replace '(?<![a-zA-Z])Fortress(?![a-zA-Z])', '堡垒'
    $r = $r -replace '(?<![a-zA-Z])Ark(?![a-zA-Z])', '方舟'
    $r = $r -replace '(?<![a-zA-Z])Citadel(?![a-zA-Z])', '要塞'
    $r = $r -replace '(?<![a-zA-Z])Bastion(?![a-zA-Z])', '堡垒'
    $r = $r -replace '(?<![a-zA-Z])Cloak(?:ed|ing)?(?![a-zA-Z])', '隐形'
    $r = $r -replace '(?<![a-zA-Z])Tractor(?![a-zA-Z])', '牵引'
    $r = $r -replace '(?<![a-zA-Z])Outpost(?![a-zA-Z])', '前哨'
    $r = $r -replace '(?<![a-zA-Z])Shipyard(?![a-zA-Z])', '船坞'
    $r = $r -replace '(?<![a-zA-Z])Barracks(?![a-zA-Z])', '兵营'
    $r = $r -replace '(?<![a-zA-Z])Factory(?![a-zA-Z])', '工厂'
    $r = $r -replace '(?<![a-zA-Z])Station(?!ary)', '站'
    $r = $r -replace '(?<![a-zA-Z])Sniper(?![a-zA-Z])', '狙击手'
    $r = $r -replace '(?<![a-zA-Z])Siege(?![a-zA-Z])', '攻城'
    $r = $r -replace '(?<![a-zA-Z])Golem(?![a-zA-Z])', '魔像'
    $r = $r -replace '(?<![a-zA-Z])Raid(?![a-zA-Z])', '突袭'
    $r = $r -replace '(?<![a-zA-Z])Blitz(?![a-zA-Z])', '闪击'
    $r = $r -replace '(?<![a-zA-Z])Death(?![a-zA-Z])', '死亡'
    $r = $r -replace '(?<![a-zA-Z])Killer(?![a-zA-Z])', '杀手'
    $r = $r -replace '(?<![a-zA-Z])Cloaked(?![a-zA-Z])', '隐形'
    $r = $r -replace '(?<![a-zA-Z])Plated(?![a-zA-Z])', '镀层'
    $r = $r -replace '(?<![a-zA-Z])Armored(?![a-zA-Z])', '装甲'
    $r = $r -replace '(?<![a-zA-Z])Protector(?![a-zA-Z])', '保护者'
    $r = $r -replace '(?<![a-zA-Z])Guardian(?![a-zA-Z])', '守护者'
    $r = $r -replace '(?<![a-zA-Z])Human(?![a-zA-Z])', '人类'
    $r = $r -replace '(?<![a-zA-Z])Spire(?![a-zA-Z])', '尖塔'
    $r = $r -replace '(?<![a-zA-Z])Zenith(?![a-zA-Z])', '天顶'
    $r = $r -replace '(?<![a-zA-Z])Neinzul(?![a-zA-Z])', '宁苏'
    $r = $r -replace '(?<![a-zA-Z])Dyson(?![a-zA-Z])', '戴森'
    $r = $r -replace '(?<![a-zA-Z])Nanocaust(?![a-zA-Z])', '纳米浩劫'
    $r = $r -replace '(?<![a-zA-Z])Militia(?![a-zA-Z])', '民兵'
    $r = $r -replace '(?<![a-zA-Z])Derelict(?![a-zA-Z])', '废弃'
    $r = $r -replace '(?<![a-zA-Z])Colony(?![a-zA-Z])', '殖民地'
    $r = $r -replace '(?<![a-zA-Z])Construction(?![a-zA-Z])', '建造'
    $r = $r -replace '(?<![a-zA-Z])Convoy(?![a-zA-Z])', '护航队'
    $r = $r -replace '(?<![a-zA-Z])Scourge(?![a-zA-Z])', '天灾'
    $r = $r -replace '(?<![a-zA-Z])Civilian(?![a-zA-Z])', '民用'
    $r = $r -replace '(?<![a-zA-Z])Raider(?![a-zA-Z])', '突击者'
    $r = $r -replace '(?<![a-zA-Z])Strike(?![a-zA-Z])', '突击'
    $r = $r -replace '(?<![a-zA-Z])Support(?![a-zA-Z])', '支援'
    $r = $r -replace '(?<![a-zA-Z])Defense(?![a-zA-Z])', '防御'
    $r = $r -replace '(?<![a-zA-Z])Escort(?![a-zA-Z])', '护航'
    $r = $r -replace '(?<![a-zA-Z])Attack(?![a-zA-Z])', '攻击'
    $r = $r -replace '(?<![a-zA-Z])Patrol(?![a-zA-Z])', '巡逻'
    $r = $r -replace '(?<![a-zA-Z])Corvette(?![a-zA-Z])', '护卫舰'
    $r = $r -replace '(?<![a-zA-Z])Mercurial(?![a-zA-Z])', '汞变'
    $r = $r -replace '(?<![a-zA-Z])Rampage(?![a-zA-Z])', '狂怒'
    $r = $r -replace '(?<![a-zA-Z])Guard(?![a-zA-Z])', '守卫'
    $r = $r -replace '(?<![a-zA-Z])Acidic(?![a-zA-Z])', '酸性'
    $r = $r -replace '(?<![a-zA-Z])Bulk(?![a-zA-Z])', '堡垒'
    $r = $r -replace '(?<![a-zA-Z])Lightshow(?![a-zA-Z])', '光秀'
    $r = $r -replace '(?<![a-zA-Z])Battlestation(?![a-zA-Z])', '要塞'
    $r = $r -replace '(?<![a-zA-Z])Pulsar(?![a-zA-Z])', '脉冲星'
    $r = $r -replace '(?<![a-zA-Z])Tachyon(?![a-zA-Z])', '快子'
    $r = $r -replace '(?<![a-zA-Z])Phase(?![a-zA-Z])', '相位'
    $r = $r -replace '(?<![a-zA-Z])Refracting(?![a-zA-Z])', '折射'
    $r = $r -replace '(?<![a-zA-Z])Lucent(?![a-zA-Z])', '光莹'
    $r = $r -replace '(?<![a-zA-Z])Charged(?![a-zA-Z])', '充能'
    $r = $r -replace '(?<![a-zA-Z])Radiant(?![a-zA-Z])', '光辉'
    $r = $r -replace '(?<![a-zA-Z])Efficient(?![a-zA-Z])', '高效'
    $r = $r -replace '(?<![a-zA-Z])Infused(?![a-zA-Z])', '灌注'
    $r = $r -replace '(?<![a-zA-Z])Goo(?![a-zA-Z])', '粘液'
    $r = $r -replace '(?<![a-zA-Z])Shrike(?![a-zA-Z])', '伯劳'
    $r = $r -replace '(?<![a-zA-Z])Mortar(?![a-zA-Z])', '迫击炮'
    $r = $r -replace '(?<![a-zA-Z])Disrupter(?![a-zA-Z])', '干扰者'
    $r = $r -replace '(?<![a-zA-Z])Hunter(?![a-zA-Z])', '猎人'
    $r = $r -replace '(?<![a-zA-Z])Coil(?![a-zA-Z])', '线圈'
    $r = $r -replace '(?<![a-zA-Z])Corrosive(?![a-zA-Z])', '腐蚀'
    $r = $r -replace '(?<![a-zA-Z])Breach(?![a-zA-Z])', '突破'
    $r = $r -replace '(?<![a-zA-Z])Blockade(?![a-zA-Z])', '封锁'
    $r = $r -replace '(?<![a-zA-Z])Consumer(?![a-zA-Z])', '消耗者'
    $r = $r -replace '(?<![a-zA-Z])Adaptor(?![a-zA-Z])', '适配者'
    $r = $r -replace '(?<![a-zA-Z])Forceshield(?![a-zA-Z])', '力场盾'
    $r = $r -replace '(?<![a-zA-Z])Chain(?![a-zA-Z])', '链式'
    $r = $r -replace '(?<![a-zA-Z])Amplifier(?![a-zA-Z])', '放大器'
    $r = $r -replace '(?<![a-zA-Z])Ionosphere(?![a-zA-Z])', '电离层'
    $r = $r -replace '(?<![a-zA-Z])Submarine(?![a-zA-Z])', '潜艇'
    $r = $r -replace '(?<![a-zA-Z])Torpedo(?![a-zA-Z])', '鱼雷'
    $r = $r -replace '(?<![a-zA-Z])Trader(?![a-zA-Z])', '商人'
    $r = $r -replace '(?<![a-zA-Z])Sapper(?![a-zA-Z])', '工兵'
    $r = $r -replace '(?<![a-zA-Z])Cargo(?![a-zA-Z])', '货物'
    $r = $r -replace '(?<![a-zA-Z])Capital(?![a-zA-Z])', '首都'
    $r = $r -replace '(?<![a-zA-Z])Trade(?![a-zA-Z])', '贸易'
    $r = $r -replace '(?<![a-zA-Z])Grand(?![a-zA-Z])', '中央'
    $r = $r -replace '(?<![a-zA-Z])HQ(?![a-zA-Z])', '总部'
    
    return $r
}

function ProcessAttr {
    param([string]$content, [string]$attr)
    $p = "(?s)($attr\s*=\s*"")((?:[^""\\]|\\.)*?)(""\s*(?:\w+=|/>|>|$))"
    return [regex]::Replace($content, $p, {
        param($m)
        $pre = $m.Groups[1].Value
        $txt = $m.Groups[2].Value
        $suf = $m.Groups[3].Value
        # Skip codes/numbers
        if ($txt -cmatch '^[A-Z0-9_.\s/-]+$' -and $txt.Length -gt 3) { return $m.Value }
        $t = Translate-Text $txt
        if ($t -eq $txt) { return $m.Value }
        return $pre + $t + $suf
    })
}

$mods = @(@{N="Leere"},@{N="DarkSphere"},@{N="AMU"},@{N="MoreSystemDefenders"},@{N="AIShieldGenerators"},@{N="KaizersMarauders"},@{N="LostHumans"},@{N="SKCivilianIndustry"})
$totalAll=0;$totalTr=0

foreach ($mod in $mods) {
    $src="$SourceBase\$($mod.N)"
    $tgt="$TargetBase\$($mod.N)"
    Write-Host "`n=== $($mod.N) ===" -ForegroundColor Cyan
    if (-not (Test-Path $src)) { Write-Host "  SKIP"; continue }
    $files=Get-ChildItem -Recurse -Filter "*.xml" $src|Where-Object{$_.FullName -notmatch '\\Source\\' -and $_.FullName -notmatch '\\Unused\\'}
    $c=0;$tr=0
    foreach ($f in $files) {
        $rel=$f.FullName.Substring($src.Length).TrimStart('\')
        $target=Join-Path $tgt $rel
        $d=Split-Path $target -Parent
        if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
        $raw=Get-Content $f.FullName -Raw -Encoding UTF8
        $has=$raw -match '(display_name|description|sidebar_text|chat_text|full_text|tooltip|choice_text|short_name|display_name_for_sidebar|description_short)\s*='
        if (-not $has) { Copy-Item $f.FullName $target -Force; $c++; continue }
        $content=$raw
        foreach ($a in @('display_name_for_sidebar','description_short','display_name','description','sidebar_text','chat_text','full_text','tooltip','choice_text','short_name')) {
            $content=ProcessAttr $content $a
        }
        $content=$content -replace '&lt;','<' -replace '&gt;','>'
        $utf8=New-Object System.Text.UTF8Encoding $true
        [System.IO.File]::WriteAllText($target, $content, $utf8)
        Write-Host "  OK: $rel"
        $tr++;$c++
    }
    Write-Host "  Files: $c | Translated: $tr" -ForegroundColor Yellow
    $totalAll+=$c;$totalTr+=$tr
}
Write-Host "`n========================" -ForegroundColor Cyan
Write-Host "DONE! Files: $totalAll | Translated: $totalTr" -ForegroundColor Green
