using Arcen.AIW2.Core;
using Arcen.Universal;
using System;

namespace Arcen.AIW2.External
{
    public class ApkalluDifficulty : ArcenDynamicTableRow, IConcurrentPoolable<ApkalluDifficulty>, IProtectedListable
    {
        public string name;
        public int Intensity;

        // Metal income generated by Outposts each second
        public int BaseMetalIncomePerSecond;
        public int MetalIncomePerSecondPer10AIP;

        // AI response to artifact captures
        public int BaseAIResponseStrength;
        public int AIResponseStrengthIncreasePerArtifact;

        // How many artifacts unlock higher-tier ships
        public int ArtifactsForTier2Ships;
        public int ArtifactsForTier3Ships;

        // Artifact spawn timing
        public int ArtifactRespawnDelay;      // seconds after an artifact is captured before the next one spawns
        public int ArtifactRespawnDelayRandomness;

        // Ranger production
        public int MaxRangersPerMajorDuru = 12;
        public int MaxDireRangersPerMajorDuru = 5;
        public int MaxRangersPerMinorDuru = 7;
        public int MaxDireRangersPerMinorDuru = 1;
        public int RangerIncomePerSecond = 20;
        public int DireRangerIncomePerSecond = 100;
        public int OutpostForRangerCap = 8;
        public int OutpostForDireRangerCap = 5;
        public int PilgrimIncome = 10;

        // Lesser Pilgrim resource conversion rates (ResourcePoints 脳 rate = amount granted)
        public FInt LesserPilgrimMetalConversion   = FInt.FromParts( 200, 000 );
        public FInt LesserPilgrimHackingConversion = FInt.FromParts( 0,  100 );
        public FInt LesserPilgrimScienceConversion = FInt.FromParts( 2,  000 );

        // Controls how quickly t (journey quality, 0鈫?) rises with hop count.
        // t = min(1, totalHops / (galaxySize * scale)). Lower = reaches max quality sooner.
        public FInt PilgrimJourneyQualityScale = FInt.FromParts( 0, 100 );

        // Fraction of a regular pilgrim's RP that always goes to the highest special resource
        // the pilgrim's tier can grant (T1鈫扲1, T2鈫扲2, T3鈫扲3). Remainder goes through the Bernstein roll.
        public FInt PilgrimGuaranteedSpecialFraction = FInt.FromParts( 0, 250 );

        // Regular Pilgrim resource conversion rates
        public FInt PilgrimMetalConversion         = FInt.FromParts( 400, 000 );
        public FInt PilgrimScienceConversion       = FInt.FromParts( 1,   000 );
        public FInt PilgrimHackingConversion       = FInt.FromParts( 0,   500 );
        public FInt PilgrimResourceOneConversion   = FInt.FromParts( 0,   200 );
        public FInt PilgrimResourceTwoConversion   = FInt.FromParts( 0,   100 );
        public FInt PilgrimResourceThreeConversion = FInt.FromParts( 0,   050 );

        // Seconds between Malware-spawned Apkallu Fissures appearing. Fissures are the Apkallu's
        // primary resource/dive opportunities (they barely spawn ships), so this scales with the
        // Apkallu's own intensity rather than the Malware difficulty: shorter = more fissures.
        public int FissureSpawnInterval = 300;

        #region Pooling
        private static ReferenceTracker RefTracker;
        private ApkalluDifficulty() : base( ThereShouldNeverBeAPublicOrInternalConstructorOnThese.IUnderstand )
        {
            if ( RefTracker == null )
                RefTracker = new ReferenceTracker( "ApkalluDifficultys" );
            RefTracker.IncrementObjectCount();
        }

        private static ConcurrentPool<ApkalluDifficulty> Pool = new ConcurrentPool<ApkalluDifficulty>( "ApkalluDifficulty", 99999,
            KeepTrackOfPooledItems.Yes_AndRefillTheMainListWithThatOnXmlReload, PoolBehaviorDuringShutdown.BlockAllThreads, delegate { return new ApkalluDifficulty(); } );

        public static ApkalluDifficulty GetFromPoolOrCreate() => Pool.GetFromPoolOrCreate();
        public override void ReturnToPool() => Pool.ReturnToPool( this );

        private static ArcenTypeAnalyzer<ApkalluDifficulty> typeAnalyzer;
        protected override void InnerSetToDefaults()
        {
            if ( typeAnalyzer == null )
                typeAnalyzer = new ArcenTypeAnalyzer<ApkalluDifficulty>( new ApkalluDifficulty() );
            typeAnalyzer.ApplyDefaults( this );
        }
        #endregion
    }

    public class ApkalluDifficultyTable : ArcenDynamicTable<ApkalluDifficulty>
    {
        public static ApkalluDifficultyTable Instance;
        public readonly ApkalluDifficulty[] RowsByIntensity = new ApkalluDifficulty[20];

        public ApkalluDifficultyTable() : base( "ApkalluDifficulty", ArcenDynamicTableType.XMLDirectory, PrimaryKeyRules.Strict, SerializedBy.Name, ReloadDuringRuntime.Allow, ReadXml.InOrderOnMainThread )
        {
            Instance = this;
        }

        public override ApkalluDifficulty GetNewRowFromPool() => ApkalluDifficulty.GetFromPoolOrCreate();

        protected override void PrepForCompleteReloadLater() { }

        public override DelReturn NodeProcessor( ArcenXMLElement Data, ApkalluDifficulty TypeDataObject )
        {
            Data.Fill( "name", ref TypeDataObject.name, !Data.ReadingPartialRecord );
            Data.Fill( "intensity", ref TypeDataObject.Intensity, !Data.ReadingPartialRecord );
            Data.Fill( "BaseMetalIncomePerSecond", ref TypeDataObject.BaseMetalIncomePerSecond, !Data.ReadingPartialRecord );
            Data.Fill( "MetalIncomePerSecondPer10AIP", ref TypeDataObject.MetalIncomePerSecondPer10AIP, !Data.ReadingPartialRecord );
            Data.Fill( "BaseAIResponseStrength", ref TypeDataObject.BaseAIResponseStrength, !Data.ReadingPartialRecord );
            Data.Fill( "AIResponseStrengthIncreasePerArtifact", ref TypeDataObject.AIResponseStrengthIncreasePerArtifact, !Data.ReadingPartialRecord );
            Data.Fill( "ArtifactsForTier2Ships", ref TypeDataObject.ArtifactsForTier2Ships, !Data.ReadingPartialRecord );
            Data.Fill( "ArtifactsForTier3Ships", ref TypeDataObject.ArtifactsForTier3Ships, !Data.ReadingPartialRecord );
            Data.Fill( "ArtifactRespawnDelay", ref TypeDataObject.ArtifactRespawnDelay, !Data.ReadingPartialRecord );
            Data.Fill( "ArtifactRespawnDelayRandomness", ref TypeDataObject.ArtifactRespawnDelayRandomness, !Data.ReadingPartialRecord );
            Data.Fill( "MaxRangersPerMajorDuru", ref TypeDataObject.MaxRangersPerMajorDuru, false );
            Data.Fill( "MaxDireRangersPerMajorDuru", ref TypeDataObject.MaxDireRangersPerMajorDuru, false );
            Data.Fill( "MaxRangersPerMinorDuru", ref TypeDataObject.MaxRangersPerMinorDuru, false );
            Data.Fill( "MaxDireRangersPerMinorDuru", ref TypeDataObject.MaxDireRangersPerMinorDuru, false );
            Data.Fill( "RangerIncomePerSecond", ref TypeDataObject.RangerIncomePerSecond, false );
            Data.Fill( "DireRangerIncomePerSecond", ref TypeDataObject.DireRangerIncomePerSecond, false );
            Data.Fill( "OutpostForRangerCap", ref TypeDataObject.OutpostForRangerCap, false );
            Data.Fill( "OutpostForDireRangerCap", ref TypeDataObject.OutpostForDireRangerCap, false );
            Data.Fill( "PilgrimIncome", ref TypeDataObject.PilgrimIncome, false );
            Data.Fill( "PilgrimJourneyQualityScale",          ref TypeDataObject.PilgrimJourneyQualityScale,          false );
            Data.Fill( "PilgrimGuaranteedSpecialFraction",    ref TypeDataObject.PilgrimGuaranteedSpecialFraction,    false );
            Data.Fill( "LesserPilgrimMetalConversion",   ref TypeDataObject.LesserPilgrimMetalConversion,   false );
            Data.Fill( "LesserPilgrimHackingConversion", ref TypeDataObject.LesserPilgrimHackingConversion, false );
            Data.Fill( "LesserPilgrimScienceConversion", ref TypeDataObject.LesserPilgrimScienceConversion, false );
            Data.Fill( "PilgrimMetalConversion",         ref TypeDataObject.PilgrimMetalConversion,         false );
            Data.Fill( "PilgrimHackingConversion",       ref TypeDataObject.PilgrimHackingConversion,       false );
            Data.Fill( "PilgrimScienceConversion",       ref TypeDataObject.PilgrimScienceConversion,       false );
            Data.Fill( "PilgrimResourceOneConversion",   ref TypeDataObject.PilgrimResourceOneConversion,   false );
            Data.Fill( "PilgrimResourceTwoConversion",   ref TypeDataObject.PilgrimResourceTwoConversion,   false );
            Data.Fill( "PilgrimResourceThreeConversion", ref TypeDataObject.PilgrimResourceThreeConversion, false );
            Data.Fill( "FissureSpawnInterval",           ref TypeDataObject.FissureSpawnInterval,           false );
            return DelReturn.Continue;
        }

        public override void DoPostInitializationPreSortingLogic_BackgroundThreads()
        {
            for ( int i = 0; i < RowsByIntensity.Length; i++ )
                RowsByIntensity[i] = null;
            for ( int i = 0; i < this.Rows.Count; i++ )
            {
                ApkalluDifficulty row = this.Rows[i];
                RowsByIntensity[row.Intensity] = row;
            }
        }

        public ApkalluDifficulty GetRowByIntensity( int intensity )
        {
            if ( intensity < 0 || intensity >= RowsByIntensity.Length )
                return null;
            return RowsByIntensity[intensity];
        }
    }
}
